package View;


import Model.Conexao;
import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LigiaBrito
 */
public class Home extends javax.swing.JFrame {

    Connection conexao;
    ResultSet rs;
    PreparedStatement pst;
    private Autenticacao autenticacao;
    String numeroConta;
    boolean verSaldo;
    
    /**
     * Creates new form Home
     */
    public Home(Autenticacao autenticacao) {
        super("Home");
        conexao = Conexao.criarConexao();
        this.autenticacao = autenticacao;
        initComponents();
        txtUser.setText(autenticacao.usuario.getNome()); 
        Table1();
        verSaldo = true;
    }
    
    public void Table1(){
        try{
            String sql = "select operacao,quantia,data,destinatario,numeroConta from extrato where numeroConta=?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, autenticacao.usuario.getNumeroConta());
            rs = pst.executeQuery();
            tblExtrato.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTipoConta = new javax.swing.JTextField();
        txtNumeroConta = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDigito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        btnMostrarDados = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDepositoConta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDepositoDigito = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDepositoAgencia = new javax.swing.JTextField();
        btnDepositoProcurar = new javax.swing.JButton();
        txtDepositoTitular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDepositoQuantia = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtTransQuantia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTransAgencia = new javax.swing.JTextField();
        txtTransDigito = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnTransProcurar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTransTitular = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnTransTransferir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTransNumConta = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txtSaqueQuantia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnSacar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExtrato = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtHomeSaldo = new javax.swing.JTextField();
        btnHomeSaldo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHomeSair = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setOpaque(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 52, -1, 186));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setText("Detalhes Da conta");

        txtTipoConta.setEditable(false);
        txtTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoContaActionPerformed(evt);
            }
        });

        txtNumeroConta.setEditable(false);

        txtAgencia.setEditable(false);

        jLabel6.setText("Digito");

        txtDigito.setEditable(false);

        jLabel4.setText("Agência");

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\profile (1).png")); // NOI18N

        jLabel5.setText("Número Da Conta");

        jLabel3.setText("Titular");

        txtTitular.setEditable(false);

        btnMostrarDados.setText("Ver dados");
        btnMostrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDadosActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo Conta");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipoConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 1, 730, 290));

        jTabbedPane1.addTab("Perfil", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\fund.png")); // NOI18N

        jLabel10.setText("Numero Da Conta");

        jLabel13.setText("Digito");

        jLabel14.setText("Agencia");

        btnDepositoProcurar.setText("Procurar");
        btnDepositoProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoProcurarActionPerformed(evt);
            }
        });

        txtDepositoTitular.setEditable(false);

        jLabel9.setText("Titular");

        jLabel12.setText("Quantia do Depósito");

        txtDepositoQuantia.setEditable(false);

        btnDepositar.setText("Depositar");
        btnDepositar.setEnabled(false);
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel26.setText("Depósito");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(10, 10, 10)
                                .addComponent(txtDepositoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDepositoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDepositoDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDepositoAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDepositoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDepositoQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDepositoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtDepositoDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtDepositoAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDepositoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtDepositoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDepositoQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)))
                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 290));

        jTabbedPane1.addTab("Depósito", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtTransQuantia.setEditable(false);

        jLabel17.setText("Agencia");

        jLabel19.setText("Digito");

        btnTransProcurar.setText("Procurar");
        btnTransProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransProcurarActionPerformed(evt);
            }
        });

        jLabel11.setText("Titular");

        txtTransTitular.setEditable(false);

        jLabel16.setText("Quantia Da Transferencia");

        btnTransTransferir.setText("Transferir");
        btnTransTransferir.setEnabled(false);
        btnTransTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransTransferirActionPerformed(evt);
            }
        });

        jLabel15.setText("Numero Da Conta");

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\money-transfer (1).png")); // NOI18N

        jLabel25.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel25.setText("Transferência");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnTransTransferir))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTransQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTransTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTransNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTransAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTransDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTransProcurar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTransNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTransAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(txtTransDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTransProcurar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txtTransTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtTransQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(btnTransTransferir)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 290));

        jTabbedPane1.addTab("Transferência", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 41, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        txtSaqueQuantia.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        jLabel20.setText("Digite a quantia que deseja sacar:");

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel27.setText("Saque");

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\wallet (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(txtSaqueQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel30)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtSaqueQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacar)
                        .addGap(94, 94, 94))))
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 290));

        jTabbedPane1.addTab("Saque", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        tblExtrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblExtrato);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel28.setText("Extrato");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 290));

        jTabbedPane1.addTab("Extrato", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1120, 320));

        txtHomeSaldo.setEditable(false);
        txtHomeSaldo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtHomeSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtHomeSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 236, 78));

        btnHomeSaldo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnHomeSaldo.setText("Visualizar Saldo");
        btnHomeSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHomeSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 160, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\bd3(1).jpg")); // NOI18N
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        txtUser.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(65, 50, 128));
        txtUser.setText("usuario");
        jPanel10.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 61, -1));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 50, 128));
        jLabel2.setText("Olá,");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btnHomeSair.setBackground(new java.awt.Color(255, 255, 255));
        btnHomeSair.setForeground(new java.awt.Color(255, 255, 255));
        btnHomeSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\sign-out.png")); // NOI18N
        btnHomeSair.setBorderPainted(false);
        btnHomeSair.setContentAreaFilled(false);
        btnHomeSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeSairActionPerformed(evt);
            }
        });
        jPanel10.add(btnHomeSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 36, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 80));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\LigiaBrito\\Downloads\\simple-gradient-minimalism-wallpaper-preview.jpg")); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        setSize(new java.awt.Dimension(740, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeSaldoActionPerformed
        String sql;
        Float saldoAtual = null;
        try{
            if(verSaldo){
                sql = "select * from conta where numeroConta=?";

                pst = conexao.prepareStatement(sql);
                pst.setString(1, autenticacao.usuario.getNumeroConta());

                rs = pst.executeQuery();

                if(rs.next()){
                    saldoAtual = Float.parseFloat(rs.getString("saldoAtual"));
                    txtHomeSaldo.setText("R$: "+saldoAtual.toString());
                    rs.close();
                    pst.close();
                }
                verSaldo = false;
                btnHomeSaldo.setText("Ocultar Saldo");
            } else{
                txtHomeSaldo.setText("");
                btnHomeSaldo.setText("Visualizar Saldo");
                verSaldo = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnHomeSaldoActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        String sql;
        Float saldoAtual = null;
        Float saqueQuantia = null;

        try{
            sql = "select * from conta where numeroConta=?";

            pst = conexao.prepareStatement(sql);
            pst.setString(1, autenticacao.usuario.getNumeroConta());

            rs = pst.executeQuery();

            if(rs.next()){
                saldoAtual = Float.parseFloat(rs.getString("saldoAtual"));
                rs.close();
                pst.close();
            }

            saqueQuantia = Float.parseFloat(txtSaqueQuantia.getText());
            saldoAtual = saldoAtual - saqueQuantia;

            sql = "update conta set saldoAtual=? where numeroConta=?";
            pst = conexao.prepareStatement(sql);

            pst.setString(1, saldoAtual.toString());
            pst.setString(2, autenticacao.usuario.getNumeroConta());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Valor Sacado");
            
            sql = "insert into extrato (operacao,quantia,data,destinatario,numeroConta) values(?,?,?,?,?)";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "saque");
            pst.setString(2, txtSaqueQuantia.getText());
            pst.setString(3, "00/00/0000");
            pst.setString(4, autenticacao.usuario.getNome());
            pst.setString(5, autenticacao.usuario.getNumeroConta());

            pst.execute();
            
            txtSaqueQuantia.setText("");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnTransTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransTransferirActionPerformed
        String sql;
        Float saldoAtualUsuario = null;
        Float saldoAtualTransferencia = null;
        Float transQuantia = null;
        try{
            sql = "select * from conta where numeroConta=?";

            pst = conexao.prepareStatement(sql);
            pst.setString(1, autenticacao.usuario.getNumeroConta());

            rs = pst.executeQuery();

            if(rs.next()){
                saldoAtualUsuario = Float.parseFloat(rs.getString("saldoAtual"));
                rs.close();
                pst.close();
            }
            if(saldoAtualUsuario > 0){
                //Transferindo o saldo do usuário...
                sql = "update conta set saldoAtual=? where numeroConta=?";
                pst = conexao.prepareStatement(sql);
                transQuantia = Float.parseFloat(txtTransQuantia.getText());
                saldoAtualUsuario = saldoAtualUsuario - transQuantia;

                pst.setString(1, saldoAtualUsuario.toString());
                pst.setString(2, autenticacao.usuario.getNumeroConta());

                pst.execute();

                //Inserindo transferencia na conta desejada...
                sql = "select * from conta where numeroConta=? and digito=? and agencia=?";

                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtTransNumConta.getText());
                pst.setString(2, txtTransDigito.getText());
                pst.setString(3, txtTransAgencia.getText());

                rs = pst.executeQuery();

                if(rs.next()){
                    saldoAtualTransferencia = Float.parseFloat(rs.getString("saldoAtual"));
                    rs.close();
                    pst.close();
                }

                sql = "update conta set saldoAtual=? where numeroConta=?";
                pst = conexao.prepareStatement(sql);

                saldoAtualTransferencia = saldoAtualTransferencia + Float.parseFloat(txtTransQuantia.getText());

                pst.setString(1, saldoAtualTransferencia.toString());
                pst.setString(2, txtTransNumConta.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null, "Transferência realizada com sucesso!");
                
                sql = "insert into extrato (operacao,quantia,data,destinatario,numeroConta) values(?,?,?,?,?)";
                pst = conexao.prepareStatement(sql);
                pst.setString(1, "transferencia");
                pst.setString(2, txtTransQuantia.getText());
                pst.setString(3, "00/00/0000");
                pst.setString(4, txtTransTitular.getText());
                pst.setString(5, autenticacao.usuario.getNumeroConta());

                pst.execute();
            }else{
                JOptionPane.showMessageDialog(null,"Não foi possivel realizar a transferência, saldo negativo");

            }
            
            txtTransNumConta.setText("");
            txtTransDigito.setText("");
            txtTransAgencia.setText("");
            txtTransQuantia.setText("");
            txtTransTitular.setText("");

            btnTransTransferir.setEnabled(false);
            txtTransQuantia.setEditable(false);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnTransTransferirActionPerformed

    private void btnTransProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransProcurarActionPerformed
        // TODO add your handling code here:
        String sql = "select * from conta where numeroConta=? and digito=? and agencia=?";
        try{
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtTransNumConta.getText());
            pst.setString(2, txtTransDigito.getText());
            pst.setString(3, txtTransAgencia.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                String titularTrans = rs.getString("titular");
                txtTransTitular.setText(titularTrans);
                rs.close();
                pst.close();
                txtTransQuantia.setEditable(true);
                btnTransTransferir.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(null, "Não foi possível localizar esta conta... Tente novamente");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            //TODO não entendi essa parte
            try{
                rs.close();
                pst.close();
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_btnTransProcurarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // TODO add your handling code here:
        String sql;
        Float saldoAtual = null;
        try{
            sql = "select * from conta where numeroConta=? and digito=? and agencia=?";

            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtDepositoConta.getText());
            pst.setString(2, txtDepositoDigito.getText());
            pst.setString(3, txtDepositoAgencia.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                saldoAtual = Float.parseFloat(rs.getString("saldoAtual"));
                rs.close();
                pst.close();
            }

            sql = "update conta set saldoAtual=? where numeroConta=?";
            pst = conexao.prepareStatement(sql);

            saldoAtual = saldoAtual + Float.parseFloat(txtDepositoQuantia.getText());

            pst.setString(1, saldoAtual.toString());
            pst.setString(2, txtDepositoConta.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Valor Depositado");
            
            sql = "insert into extrato (operacao,quantia,data,destinatario,numeroConta) values(?,?,?,?,?)";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "deposito");
            pst.setString(2, txtDepositoQuantia.getText());
            pst.setString(3, "00/00/0000");
            pst.setString(4, txtDepositoTitular.getText());
            pst.setString(5, autenticacao.usuario.getNumeroConta());

            pst.execute();
            
            txtDepositoConta.setText("");
            txtDepositoDigito.setText("");
            txtDepositoAgencia.setText("");
            txtDepositoQuantia.setText("");
            txtDepositoTitular.setText("");

            btnDepositar.setEnabled(false);
            txtDepositoQuantia.setEditable(false);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnDepositoProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoProcurarActionPerformed
        // TODO add your handling code here:
        String sql = "select * from conta where numeroConta=? and digito=? and agencia=?";
        try{
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtDepositoConta.getText());
            pst.setString(2, txtDepositoDigito.getText());
            pst.setString(3, txtDepositoAgencia.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                String titularDeposito = rs.getString("titular");
                txtDepositoTitular.setText(titularDeposito);
                rs.close();
                pst.close();
                txtDepositoQuantia.setEditable(true);
                btnDepositar.setEnabled(true);
            } else{
                JOptionPane.showMessageDialog(null, "Não foi possível localizar esta conta... Tente novamente");
            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            //TODO não entendi essa parte
            try{
                rs.close();
                pst.close();
            }catch(Exception e){

            }
        }

    }//GEN-LAST:event_btnDepositoProcurarActionPerformed

    private void btnMostrarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDadosActionPerformed
        // TODO add your handling code here:

        String sql = "select * from conta where numeroConta=?";
        try{
            pst = conexao.prepareStatement(sql);
            pst.setString(1, autenticacao.usuario.getNumeroConta());
            rs = pst.executeQuery();

            if(rs.next()){
                String titular = rs.getString("titular");
                txtTitular.setText(titular);

                String numConta = rs.getString("numeroConta");
                txtNumeroConta.setText(numConta);

                String agencia = rs.getString("agencia");
                txtAgencia.setText(agencia);

                String digito = rs.getString("digito");
                txtDigito.setText(digito);

                String tipoConta = rs.getString("tipoDaConta");
                txtTipoConta.setText(tipoConta);

                rs.close();
                pst.close();
            } else{
                JOptionPane.showMessageDialog(null, "");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnMostrarDadosActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        Table1();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnHomeSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeSairActionPerformed
        // TODO add your handling code here:
                setVisible(false);
                Autenticacao ob = new Autenticacao();
                ob.setVisible(true);
              
    }//GEN-LAST:event_btnHomeSairActionPerformed

    private void txtTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(new Autenticacao()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnDepositoProcurar;
    private javax.swing.JButton btnHomeSair;
    private javax.swing.JButton btnHomeSaldo;
    private javax.swing.JButton btnMostrarDados;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnTransProcurar;
    private javax.swing.JButton btnTransTransferir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblExtrato;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtDepositoAgencia;
    private javax.swing.JTextField txtDepositoConta;
    private javax.swing.JTextField txtDepositoDigito;
    private javax.swing.JTextField txtDepositoQuantia;
    private javax.swing.JTextField txtDepositoTitular;
    private javax.swing.JTextField txtDigito;
    private javax.swing.JTextField txtHomeSaldo;
    private javax.swing.JTextField txtNumeroConta;
    private javax.swing.JTextField txtSaqueQuantia;
    private javax.swing.JTextField txtTipoConta;
    private javax.swing.JTextField txtTitular;
    private javax.swing.JTextField txtTransAgencia;
    private javax.swing.JTextField txtTransDigito;
    private javax.swing.JTextField txtTransNumConta;
    private javax.swing.JTextField txtTransQuantia;
    private javax.swing.JTextField txtTransTitular;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
